# infra/docker-compose.yml
version: '3.8'

services:
  frontend:
    build:
      context: ../frontend
    ports:
      - "3000:3000"
    volumes:
      - ../frontend:/app
      - /app/node_modules
    environment:
      - VITE_API_BASE_URL=http://backend:8000/api/v1
      - VITE_ENABLE_MOCK_DATA=true
    depends_on:
      - backend

  backend:
    build:
      context: ../backend
    ports:
      - "8000:8000"
    volumes:
      - ../backend:/app
    environment:
      - DATABASE_URL=sqlite:///./baseball_betting.db
      - SPORTSDATAIO_API_KEY=${SPORTSDATAIO_API_KEY}
      - ODDS_API_KEY=${ODDS_API_KEY}
      - OPENAI_API_KEY=${OPENAI_API_KEY}
      - WEATHER_API_KEY=${WEATHER_API_KEY}
      - ENV=development
    command: uvicorn app.main:app --host 0.0.0.0 --port 8000 --reload

  nginx:
    image: nginx:alpine
    ports:
      - "80:80"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./nginx/sites-enabled:/etc/nginx/sites-enabled
    depends_on:
      - frontend
      - backend